"""empty message

Revision ID: 30a0e82766b2
Revises: bad7ac17c6a8
Create Date: 2024-02-19 19:08:59.820520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30a0e82766b2'
down_revision: Union[str, None] = 'bad7ac17c6a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(), nullable=False))
    op.create_unique_constraint("user_email_key", 'user', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("user_email_key", 'user', type_='unique')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
