DATABASE_USER = "admin"
DATABASE_PASSWORD = "123"
DATABASE_HOST = "localhost"
DATABASE_PORT = 5432
DATABASE_NAME = "test_db"

SQL_ECHO = True

TOKEN_EXP_IN_MINUTES = 10

SECRET_JWT_KEY = "Fynpg%WsUeZu0::*>#5gd]d%gBdv%sdLMoG}n9,4+)-@HGLV]):@8*}x_VHW.EW9EVBe^r2E+vzkwCnv?wv+uR^3D5?YP>QKnLM2"
